name: Deploy website to GitHub Pages

on:
  push:
    branches: ["master"]

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.github_pages_url }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Vite Github Pages Deploy
        uses: skywarth/vite-github-pages-deployer@v1.5.0
        id: deployment
        public_base_path: /
        package_manager: pnpm
